### ISSUE TITLE
Starting Leap process and reading data

### ISSUE THREAD

**Issue by mlang251** [vsuha/AudioEffectsBox#11]
Refer to the [issue_Leap branch code for appServer.js](https://github.com/vsuha/AudioEffectsBox/blob/issue_Leap/server_ui/app/appServer.js) lines 24-37

To run the Leap Python process within Node, I tried a couple libraries, [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options), which is a default Node library, and [python-shell](https://github.com/extrabacon/python-shell) posted by extrabacon. Both of these libraries work by running the Python script as a child process of the Node server, and both can read the stdout when the Python script prints something to the terminal. The problem is that both expect the Python process to be run and then exited all at once, but our Leap script needs to run continuously in the background. This confuses the server and causes it to either crash or refuse the data from stdout. I presume this is how any child process would work no matter which library we use, so there are a few ways around this issue that I can think of:

1. Manually launching the Leap process and having it output to a port with OSC, and having the server listening on the same port - this is simple to set up but I personally don't like it because we will have to transmit through OSC to the server, and then the server will have to transmit to the UI and to Max. Yes we can have the Leap talk directly to the UI and Max but that defeats the purpose of having the server as a central hub of communication for the system.
2. Maybe there is a way to code the Python process on a second thread, so that it can be run in the background while the server is running. This is a hard maybe, I doubt it and I have not looked into it at all.
3. Convert the Leap code into a Javascript application and use [the Javascript SDK](https://developer.leapmotion.com/documentation/v2/javascript/index.html) instead of Python. I haven't looked much into this either but it [should interface nicely with Node](https://github.com/motdotla/writings/blob/master/articles/posts/beginners-guide-to-leap-motion-with-nodejs.md)

**Comment by AudioEffectsBox** [comment]
Hmmm this is def a big issue. I honestly have no experience with threading. We could split up into two teams again where one attempts #2 and another attempts #3. But def worth discussing tomorrow. Thanks for diving into this.
