### ISSUE TITLE
"re-mapping" an axis not working

### ISSUE THREAD

**Issue by nknaian** [vsuha/AudioEffectsBox#15]
Reproduction steps:
1. create 3 reverb effects in the UI
2. In the UI, set x to parameter Crossover on reverb 2
3. In the UI, sex x to parameter Liveness on reverb 3

Expected result:
Data sent over /xyzMap port: {"reverb2":{"param":"Crossover","axis":"n"}}
Data sent over /xyzMap port: {"reverb3":{"param":"Liveness","axis":"x"}}

Actual result:
Data sent over /xyzMap port: {"reverb2":{"param":"Crossover","axis":"x"}}
Data sent over /xyzMap port: {"reverb3":{"param":"Liveness","axis":"x"}}

**Comment by mlang251** [comment]
I thought we decided the clearing of the old axis mapping would happen within Max? If not I can add a few lines, it's probably a lot easier to handle this on the server than in Max
