### ISSUE TITLE
Leap only sends coordinates when console window is selected

### ISSUE THREAD

**Issue by vsuha** [vsuha/AudioEffectsBox#7]
*We need to figure a way to get the max patch to run without having the python console window actively selected. 
*The max patch should be able to work by itself.

Look into having the leap run in the background while other apps are running.

**Comment by mlang251** [comment]
I committed a change to fix this but it needs to be tested with main.py running in the background and Max running in the foreground

**Comment by vsuha** [comment]
sweet, we can test it on Sunday!

**Comment by vsuha** [comment]
closed with commit e386986
